################################################################################
# Environment script generated by ilcsoft-install on Mon Mar 11 13:50:46 2013
# for Eutelescope located at [ /afs/cern.ch/user/m/mbenoit/TestBeam_Analysis/ILCsoft/EUTelescopeInstallation/Eutelescope/v00-08-00 ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export MAKEOPTS="-j3"
export CXX="g++"
export ILCSOFT_CMAKE="/afs/cern.ch/user/m/mbenoit/TestBeam_Analysis/ILCsoft/EUTelescopeInstallation/ILCSoft.cmake"
export CC="gcc"
export FC="gfortran"
export ILCSOFT_CMAKE_ENV="/afs/cern.ch/user/m/mbenoit/TestBeam_Analysis/ILCsoft/EUTelescopeInstallation/ILCSoft.cmake.env.sh"


#--------------------------------------------------------------------------------
#     Eutelescope
#--------------------------------------------------------------------------------
export EUDAQ="/afs/cern.ch/user/m/mbenoit/TestBeam_Analysis/ILCsoft/EUTelescopeInstallation/Eutelescope/v00-08-00/eudaq/trunk"
export MILLEPEDEII="/afs/cern.ch/user/m/mbenoit/TestBeam_Analysis/ILCsoft/EUTelescopeInstallation/Eutelescope/v00-08-00/millepede2/trunk"
export MILLEPEDEII_VERSION="trunk"
export EUDAQ_VERSION="trunk"
export EUTELESCOPE="/afs/cern.ch/user/m/mbenoit/TestBeam_Analysis/ILCsoft/EUTelescopeInstallation/Eutelescope/v00-08-00"
export PATH="$MILLEPEDEII:$EUTELESCOPE/bin:$PATH"
export LD_LIBRARY_PATH="$EUTELESCOPE/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ILCSOFT/v01-16/gear/v01-02-02"
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     ROOT
#--------------------------------------------------------------------------------
export ROOTSYS="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ROOT/v5-28-00f"
export PATH="$ROOTSYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/afs/cern.ch/sw/lcg/external/clhep/2.1.1.0/x86_64-slc5-gcc41-opt"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     RAIDA
#--------------------------------------------------------------------------------
export RAIDA_HOME="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ILCSOFT/v01-16/RAIDA/v01-06-02"
export PATH="$RAIDA_HOME/bin:$PATH"


#--------------------------------------------------------------------------------
#     Marlin
#--------------------------------------------------------------------------------
export MARLIN="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ILCSOFT/v01-16/Marlin/v01-04"
export PATH="$MARLIN/bin:$PATH"
export MARLIN_DLL="/afs/cern.ch/user/m/mbenoit/TestBeam_Analysis/ILCsoft/EUTelescopeInstallation/Eutelescope/v00-08-00/lib/libEutelescope.so:$MARLIN_DLL"


#--------------------------------------------------------------------------------
#     LCCD
#--------------------------------------------------------------------------------
export LCCD="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ILCSOFT/v01-16/lccd/v01-02"


#--------------------------------------------------------------------------------
#     CondDBMySQL
#--------------------------------------------------------------------------------
export COND_DB_DEBUGLOG="/dev/stdout"
export CondDBMySQL="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ILCSOFT/v01-16/CondDBMySQL/CondDBMySQL_ILC-0-9-5"
export LD_LIBRARY_PATH="$CondDBMySQL/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ILCSOFT/v01-16/lcio/v02-03-01"
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GSL
#--------------------------------------------------------------------------------
export GSL_HOME="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/GSL/1.14"
export PATH="$GSL_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$GSL_HOME/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CED
#--------------------------------------------------------------------------------
export PATH="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ILCSOFT/v01-16/CED/v01-07/bin:$PATH"


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------
export PATH="/afs/cern.ch/sw/lcg/external/CMake/2.8.6/x86_64-slc5-gcc43-opt/bin:$PATH"


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/afs/cern.ch/eng/clic/software/x86_64-slc5-gcc41/ILCSOFT/v01-16/ilcutil/v01-00"
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
