
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: MFS Parameters
*
*******************************************************************/

#ifndef _MFS_CONFIG_H
#define _MFS_CONFIG_H
#include <stdio.h>
#include <xilmfs.h>
#define MFS_NUMBYTES  2048000
#define MFS_BASE_ADDRESS 0xa5000000
#define MFS_INIT_TYPE  MFSINIT_IMAGE
#endif
